export default [{
  title: '角色管理',
  path: '/roles',
  icon: 'el-icon-s-custom',
  // code: 'menu.role', // 权限code
}, {
  title: '404页面',
  path: '/error/404',
  icon: 'el-icon-warning-outline',
}, {
  title: '401页面',
  path: '/error/401',
  icon: 'el-icon-info',
}, {
  title: '子系统列表',
  path: '/subsystem',
  icon: 'el-icon-notebook-2',
}, {
  title: '范例',
  path: '/examples',
  icon: 'el-icon-menu',
  children: [{
    title: '例子',
    path: '/examples/example',
    icon: 'el-icon-film',
  }, {
    title: '图标',
    path: '/examples/icon',
    icon: 'el-icon-tickets',
  }, {
    title: '按钮',
    path: '/examples/button',
    icon: 'el-icon-mouse',
  }, {
    title: '表格',
    path: '/examples/table',
    icon: 'el-icon-wallet',
  }, {
    title: '消息提示',
    path: '/examples/message',
    icon: 'el-icon-news',
  }, {
    title: '消息通知',
    path: '/examples/notify',
    icon: 'el-icon-date',
  }, {
    title: '弹窗',
    path: '/examples/message-box',
    icon: 'el-icon-connection',
  }, {
    title: '对话框',
    path: '/examples/dialog',
    icon: 'el-icon-date',
  }, {
    title: '滚动到顶部',
    path: '/examples/scrolltotop',
    icon: 'el-icon-date',
  }, {
    title: '可拖动对话框',
    path: '/examples/drag-dialog',
    icon: 'el-icon-date',
  }, {
    title: '标签页',
    path: '/examples/tabs',
    icon: 'el-icon-date',
  }, {
    title: '表单',
    path: '/examples/form',
    icon: 'el-icon-date',
  }],
}];
