spring:
  datasource:
    ##测试服
#    url: jdbc:mysql://10.0.160.219:3306/sprc_acm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: i<Wrftox8r%
    url: jdbc:mysql://10.0.139.239:3306/eprs_acm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
bachelor:
  iam:
  ########################################↓权限配置↓########################################
    client:
      id: f74381f3ad4b4fb681cbf1e6e2fd74f5
      secret: ff5aadc7c33e4a398800575a4389512b
  ########################################↑权限配置↑########################################