server:
  port: 8740
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
#    registerWithEureka: false
#    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8740/eureka
  server:
    response-cache-update-interval-ms: 3000
    response-cache-auto-expiration-in-seconds: 180
    eviction-interval-timer-in-ms: 3000
spring:
  application:
    name: bachelor-ms-eureka-server